###Самостоятельное задание

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

######Задача1

1. Повторите анализ для других видов моделей. Используйте 5-10 разных классов моделей. Подсчитывайте только метрики на тестовой выборке.

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/koroteevmv/ML_course/2024/ML4.1%20metrics/heart.csv')

In [ ]:
y = data["output"]
X = data.drop("output", axis=1)

In [ ]:
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC, SVR
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly_transform = PolynomialFeatures(degree=2)
poly_transform.fit(X)
X_transform = poly_transform.transform(X)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X_transform, y, train_size=0.8)

In [ ]:
models = {"Логистическая регрессия": LogisticRegression(max_iter=10000),
          "Метод опорных векторов": SVC(),
          "Перцептрон": MLPClassifier(),
          "Деревья решений": DecisionTreeClassifier(),
          "Метод k ближайших соседей": KNeighborsClassifier(),
          "Гауссовский Наивный Байес": GaussianNB()
          }
table = pd.DataFrame()

In [ ]:
def learn_model(models, x_train, x_test, y_train, y_test):
  global table
  for name, model in models.items():
    model.fit(x_train, y_train)

    y_test_pred = model.predict(x_test)

    metrics = pd.DataFrame({
          'Accuracy': accuracy_score(y_test, y_test_pred),
          'f1 score': f1_score(y_test, y_test_pred),
          'precision score': precision_score(y_test, y_test_pred),
          'recall score': recall_score(y_test, y_test_pred)
          },
          index=[name]
      )
    table = pd.concat([table, metrics])
    print(name)
    print(confusion_matrix(y_test, y_test_pred), '\n')
  return table


In [ ]:
learn_model(models, x_train, x_test, y_train, y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Логистическая регрессия
[[24  8]
 [ 0 29]] 

Метод опорных векторов
[[12 20]
 [ 3 26]] 

Перцептрон
[[27  5]
 [ 6 23]] 

Деревья решений
[[24  8]
 [ 8 21]] 

Метод k ближайших соседей
[[18 14]
 [ 7 22]] 

Гауссовский Наивный Байес
[[28  4]
 [ 1 28]] 



Accuracy  f1 score  precision score  recall score
Логистическая регрессия    0.868852  0.878788         0.783784      1.000000
Метод опорных векторов     0.622951  0.693333         0.565217      0.896552
Перцептрон                 0.819672  0.807018         0.821429      0.793103
Деревья решений            0.737705  0.724138         0.724138      0.724138
Метод k ближайших соседей  0.655738  0.676923         0.611111      0.758621
Гауссовский Наивный Байес  0.918033  0.918033         0.875000      0.965517

2. Повторите анализ для другого датасета по вашему выбору. Используйте несколько моделей для сравнения. Используйте датасет для множественной классификации.

In [ ]:
from sklearn.datasets import fetch_openml

In [ ]:
datas = fetch_openml('vertebra-column')

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:301: UserWarning: Multiple active versions of the dataset matching the name vertebra-column exist. Versions may be fundamentally different, returning version 1.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
print(datas.DESCR)

**Author**: Guilherme de Alencar Barreto, Ajalmar R. da Rocha Neto, Henrique Antonio Fonseca da Mota Filho       
**Source**: UCI  
**Please cite**:   

* Dataset Title: Vertebra Column - 3 classes

* Abstract:   
Data set containing values for six biomechanical features used to classify orthopaedic patients into 3 classes (normal, disk hernia or spondilolysthesis) or 2 classes (normal or abnormal).

* Source:

Guilherme de Alencar Barreto (guilherme '@' deti.ufc.br) & Ajalmar R. da Rocha Neto (ajalmar '@' ifce.edu.br), Department of Teleinformatics Engineering, Federal University of Ceará, Fortaleza, Ceará, Brazil. 

Henrique Antonio Fonseca da Mota Filho (hdamota '@' gmail.com), Hospital Monte Klinikum, Fortaleza, Ceará, Brazil.


Data Set Information:

Biomedical data set built by Dr. Henrique da Mota during a medical residence period in the Group of Applied Research in Orthopaedics (GARO) of the Centre Médico-Chirurgical de Réadaptation des Massues, Lyon, France. The data have been

In [ ]:
X, y = datas.data, datas.target

In [ ]:
datas.data.describe()

V1          V2          V3          V4          V5          V6
count  310.000000  310.000000  310.000000  310.000000  310.000000  310.000000
mean    60.496653   17.542822   51.930930   42.953831  117.920655   26.296694
std     17.236520   10.008330   18.554064   13.423102   13.317377   37.559027
min     26.147921   -6.554948   14.000000   13.366931   70.082575  -11.058179
25%     46.430294   10.667069   37.000000   33.347122  110.709196    1.603727
50%     58.691038   16.357689   49.562398   42.404912  118.268178   11.767933
75%     72.877696   22.120395   63.000000   52.695889  125.467675   41.287352
max    129.834041   49.431864  125.742386  121.429566  163.071041  418.543082

In [ ]:
X.isna().sum()

V1    0
V2    0
V3    0
V4    0
V5    0
V6    0
dtype: int64

In [ ]:
x_train_2, x_test_2, y_train_2, y_test_2 = train_test_split(X, y, train_size=0.8)

In [ ]:
def learn_model_mult(models, x_train, x_test, y_train, y_test):
  for name, model in models.items():
    model.fit(x_train, y_train)

    y_test_pred = model.predict(x_test)

    classes_name = ['class 0', 'class 1', 'class 2']

    print(name, '\n')
    print(classification_report(y_test, y_test_pred, target_names=classes_name))
    print(confusion_matrix(y_test, y_test_pred), '\n')

In [ ]:
learn_model_mult(models, x_train_2, x_test_2, y_train_2, y_test_2)

Логистическая регрессия 

              precision    recall  f1-score   support

     class 0       0.86      0.63      0.73        19
     class 1       0.70      0.84      0.76        19
     class 2       0.96      1.00      0.98        24

    accuracy                           0.84        62
   macro avg       0.84      0.82      0.82        62
weighted avg       0.85      0.84      0.84        62

[[12  7  0]
 [ 2 16  1]
 [ 0  0 24]] 

Метод опорных векторов 

              precision    recall  f1-score   support

     class 0       0.80      0.42      0.55        19
     class 1       0.59      0.84      0.70        19
     class 2       0.96      1.00      0.98        24

    accuracy                           0.77        62
   macro avg       0.78      0.75      0.74        62
weighted avg       0.80      0.77      0.76        62

[[ 8 11  0]
 [ 2 16  1]
 [ 0  0 24]] 

Перцептрон 

              precision    recall  f1-score   support

     class 0       0.73      0.42      0.

3. Повторите анализ для датасета, предназначенного для решения задачи регрессии. Используйте все метрики качества регрессии, изученные на лекции. Постройте 5 - 10 разных моделей регрессии.

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, mean_squared_log_error, mean_absolute_percentage_error, median_absolute_error,max_error

In [ ]:
data_3 = fetch_openml('analcatdata_supreme')
print(data_3.DESCR)

**Author**:   
**Source**: Unknown - Date unknown  
**Please cite**:   

analcatdata    A collection of data sets used in the book "Analyzing Categorical Data,"
by Jeffrey S. Simonoff, Springer-Verlag, New York, 2003. The submission
consists of a zip file containing two versions of each of 84 data sets,
plus this README file. Each data set is given in comma-delimited ASCII
(.csv) form, and Microsoft Excel (.xls) form.

NOTICE: These data sets may be used freely for scientific, educational and/or
noncommercial purposes, provided suitable acknowledgment is given (by citing
the above-named reference).

Further details concerning the book, including information on statistical software
(including sample S-PLUS/R and SAS code), are available at the web site

http://www.stern.nyu.edu/~jsimonof/AnalCatData


Information about the dataset
CLASSTYPE: numeric
CLASSINDEX: none specific


Note: Quotes, Single-Quotes and Backslashes were removed, Blanks replaced
with Underscores

Downloaded from ope

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:301: UserWarning: Multiple active versions of the dataset matching the name analcatdata_supreme exist. Versions may be fundamentally different, returning version 1.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
X_3, y_3 = data_3.data, data_3.target

In [ ]:
X_3.describe()

Actions_taken      Liberal  Unconstitutional  Precedent_alteration  \
count    4052.000000  4052.000000       4052.000000           4052.000000   
mean        0.108835     0.519743          0.078233              0.022952   
std         0.644557     0.499672          0.268571              0.149768   
min         0.000000     0.000000          0.000000              0.000000   
25%         0.000000     0.000000          0.000000              0.000000   
50%         0.000000     1.000000          0.000000              0.000000   
75%         0.000000     1.000000          0.000000              0.000000   
max        11.000000     1.000000          1.000000              1.000000   

         Unanimous  Year_of_decision  Lower_court_disagreement  
count  4052.000000       4052.000000               4052.000000  
mean      0.337611       1972.348470                  0.225568  
std       0.472954          9.851025                  0.418007  
min       0.000000       1953.000000                  0.000000  
25%       0.000000       1964.000000                  0.000000  
50%       0.000000       1973.000000                  0.000000  
75%       1.000000       1981.000000                  0.000000  
max       1.000000       1988.000000                  1.000000

In [ ]:
x_train_3, x_test_3, y_train_3, y_test_3 = train_test_split(X_3, y_3, train_size=0.8)

In [ ]:
regression_models = {"Линейная регрессия": LinearRegression(),
          "Перцептрон": MLPRegressor(),
          "Деревья решений": DecisionTreeRegressor(),
          "Метод k ближайших соседей": KNeighborsRegressor(),
         "Случайный лес": RandomForestRegressor(),
          "Метод опорных векторов": SVR()
          }

table_regression = pd.DataFrame()

In [ ]:
def learn_reg_model(models, x_train, x_test, y_train, y_test):
  global table_regression
  for name, model in models.items():
    model.fit(x_train, y_train)

    y_test_pred = model.predict(x_test)

    metrics = pd.DataFrame({
          'r2': r2_score(y_test, y_test_pred),
          'MAE': mean_absolute_error(y_test, y_test_pred),
          'MSE': mean_squared_error(y_test, y_test_pred),
          'MSLE': mean_squared_log_error(y_test, y_test_pred),
          'MAPE': mean_absolute_percentage_error(y_test, y_test_pred),
          'MedianAS': median_absolute_error(y_test, y_test_pred),
           'MAX Error': max_error(y_test, y_test_pred)
          },
          index=[name]
      )
    table_regression = pd.concat([table_regression, metrics])
  return table_regression

In [ ]:
result_table = learn_reg_model(regression_models, x_train_3, x_test_3, y_train_3, y_test_3)

poly_transform_3 = PolynomialFeatures(degree=2)
poly_transform_3.fit(X_3)
X_3_transform = poly_transform_3.transform(X_3)

x_train_3t, x_test_3t, y_train_3t, y_test_3t = train_test_split(X_3_transform, y_3, train_size=0.8)

poly_linear_reg = {'Полиномиальная регрессия': LinearRegression()}

table_reg = learn_reg_model(poly_linear_reg, x_train_3t, x_test_3t, y_train_3t, y_test_3t)

pd.concat([table_reg, result_table])

r2       MAE       MSE      MSLE  \
Полиномиальная регрессия   0.785621  0.195521  0.058597  0.013848   
Линейная регрессия         0.424768  0.302138  0.160373  0.036813   
Перцептрон                -0.051451  0.363338  0.293141  0.061374   
Деревья решений            0.964021  0.017412  0.010031  0.001773   
Метод k ближайших соседей  0.982374  0.015650  0.004914  0.001126   
Случайный лес              0.981332  0.015356  0.005205  0.000991   
Метод опорных векторов     0.012318  0.267265  0.275363  0.060570   

                                   MAPE      MedianAS  MAX Error  
Полиномиальная регрессия   8.692312e+13  1.822498e-01   0.990670  
Линейная регрессия         1.913734e+14  2.620807e-01   1.565407  
Перцептрон                 2.782376e+14  2.697107e-01   2.343964  
Деревья решений            2.438335e+12  9.370282e-14   1.610000  
Метод k ближайших соседей  4.598003e+12  0.000000e+00   0.910000  
Случайный лес              2.447654e+12  3.730349e-14   0.910000  
Метод опорных векторов     2.840762e+14  9.569905e-02   2.135607